repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-lasvphylo_logo_light.png
    - docs/images/nf-core-lasvphylo_logo_light.png
    - docs/images/nf-core-lasvphylo_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config: false
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - CITATIONS.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-lasvphylo_logo_light.png
    - docs/images/nf-core-lasvphylo_logo_light.png
    - docs/images/nf-core-lasvphylo_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml

template:
  org: Joon-Klaps
  name: lasvphylo
  description: lasvphylo  is a pipeline for creating a high quality alignment of LASV
    segements and a maximum likelihood tree
  author: Joon Klaps
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - ci
    - igenomes
    - multiqc
    - fastqc
    - seqera_platform
    - gpu
    - codespaces
    - vscode
    - citations
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
